before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - psql --version
  - sudo /etc/init.d/postgresql stop
  - sudo apt-get -y --purge remove postgresql libpq-dev libpq5 postgresql-client-common postgresql-common
  - sudo rm -rf /var/lib/postgresql
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo sh -c "echo deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main $PGVERSION >> /etc/apt/sources.list.d/postgresql.list"
  - sudo apt-get update -qq
  - sudo apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::="--force-confnew" install postgresql-$PGVERSION postgresql-server-dev-$PGVERSION
  - sudo chmod 777 /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - sudo echo "local   all         postgres                          trust" > /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - sudo echo "local   all         all                               trust" >> /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - sudo echo "host    all         all         127.0.0.1/32          trust" >> /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - sudo echo "host    all         all         ::1/128               trust" >> /etc/postgresql/$PGVERSION/main/pg_hba.conf
  - sudo /etc/init.d/postgresql restart
  - if [ "$CC" = "gcc" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CC" = "gcc" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

before_script:
  - $CXX --version
  - pushd ..
  - git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
  - export PATH="$PATH":`pwd`/depot_tools
  - popd
  - pushd ..
  - fetch v8; cd v8
  - export tag=`git ls-remote |grep tags/$v8 | cut -f 3 -d / | sort -k 3,3n -k 4,4n -t .|tail -1`
  - git checkout $tag && gclient sync > /dev/null
  - git describe --always
  - env CXXFLAGS=-fPIC make dependencies > /dev/null || true
  - env CXXFLAGS=-fPIC make native -j8
  - sudo cp -rf include/* /usr/include
  - sudo cp -f out/native/obj.target/tools/gyp/*.a out/native/obj.target/third_party/icu/*.a /usr/lib
  - sudo install -v out/native/d8 /usr/bin/d8
  - popd
  - createuser -U postgres -s travis


env:
  matrix:
    - PGVERSION=9.4 v8=4.2
    - PGVERSION=9.4 v8=4.1
    - PGVERSION=9.4 v8=3.32
    - PGVERSION=9.4 v8=3.31
    - PGVERSION=9.4 v8=3.30
    - PGVERSION=9.4 v8=3.18
    - PGVERSION=9.4 v8=3.14
    - PGVERSION=9.3 v8=4.2
    - PGVERSION=9.3 v8=4.1
    - PGVERSION=9.4 v8=3.32
    - PGVERSION=9.3 v8=3.31
    - PGVERSION=9.3 v8=3.30
    - PGVERSION=9.3 v8=3.18
    - PGVERSION=9.3 v8=3.14
    - PGVERSION=9.2 v8=4.2
    - PGVERSION=9.2 v8=4.1
    - PGVERSION=9.4 v8=3.32
    - PGVERSION=9.2 v8=3.31
    - PGVERSION=9.2 v8=3.30
    - PGVERSION=9.2 v8=3.18
    - PGVERSION=9.2 v8=3.14

language: cpp
compiler:
#  - clang
  - gcc

script:
  - make V8_SRCDIR=/usr CUSTOM_CC=$CXX V8_OUTDIR=/usr/lib SHLIB_LINK="`echo libv8_base.a libv8_snapshot.a libv8_libplatform.a libv8_libbase.a libicui18n.a libicuuc.a libicudata.a  | xargs -n1 | xargs -I % echo /usr/lib/% | xargs`"
  - sudo make install && make installcheck

after_script:
  - cat regression.diffs || true
