before_script:
  - sudo cat /etc/postgresql/9.1/main/pg_hba.conf
  - sudo cat /etc/postgresql/9.1/main/pg_ident.conf
  - sudo cat /etc/postgresql/9.1/main/postgresql.conf
  - sudo /etc/init.d/postgresql stop
  - sudo apt-get -y --purge remove postgresql
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main 9.3" >> /etc/apt/sources.list.d/postgresql.list'
  - sudo apt-get update -qq
  - sudo apt-get -q -y -o Dpkg::Options::=--force-confdef install postgresql-client-9.3 postgresql-9.3 postgresql-server-dev-9.3
  - sudo chmod 777 /etc/postgresql/9.3/main/pg_hba.conf
  - sudo echo "local   all         postgres                          trust" > /etc/postgresql/9.3/main/pg_hba.conf
  - sudo echo "local   all         all                               trust" >> /etc/postgresql/9.3/main/pg_hba.conf
  - sudo echo "host    all         all         127.0.0.1/32          trust" >> /etc/postgresql/9.3/main/pg_hba.conf
  - sudo echo "host    all         all         ::1/128               trust" >> /etc/postgresql/9.3/main/pg_hba.conf
  - sudo echo "host    all         all         0.0.0.0/0             trust" >> /etc/postgresql/9.3/main/pg_hba.conf
  - sudo echo "host    all         all         0.0.0.0 255.255.255.255 trust" >> /etc/postgresql/9.3/main/pg_hba.conf
  - sudo /etc/init.d/postgresql restart
  - git clone -b $v8 --depth 10 git://github.com/v8/v8.git
  - cd v8 && git describe --always
  - make dependencies && make native library=shared -j8
  - sudo install -v --mode=0644 include/* /usr/include
  - sudo install -v --mode=0644 out/native/lib.target/libv8.so /usr/lib/libv8.so
  - sudo install -v out/native/d8 /usr/bin/d8
  - cd ..

env:
  - v8=3.17

language: cpp
compiler:
  - clang

script: make
